default_roles:
  - system
  - 1password
  - ansible-lint
  - asciinema
  - atuin
  - azure
  - bash
  - bat
  - btop
  - chirp
  - claude-code
  - claude-desktop
  - code
  - devtunnel
  - discord
  # - edge
  # - fonts
  # - foot
  # - fzf
  # - gemini-cli
  # - gh
  # - git
  - google-chrome
  # - google-cloud
  # - kanshi
  # - libreoffice
  # - lsd
  # - mc
  # - mullvad
  # - ncdu
  # - neovim
  # - networkmanagerdmenu
  # - npm
  # - nvm
  # - obsidian
  # - phpstorm
  # - podman
  # - qbittorrent
  # - rclone
  # - ripgrep
  # - rofi
  # - rsync
  # - screenshots
  # - ssh
  # - sshfs
  # - starship
  # - sway
  # - telnet
  # - tldr
  # - tmux
  # - vlc
  # - wireguard
  # - ytdlp
  # - zoxide
  - zsh
