default_roles:
  - system
  - 1password
  - ansible-lint
  - asciinema
  - atuin
  - azure
  - bash
  - bat
  - btop
  - chirp
  - claude-code
  - claude-desktop
  - code
  - devtunnel
  - discord
  - edge
  - fonts
  - fzf
  - gemini-cli
  - gh
  - git
  - google-chrome
  - google-cloud
  - iterm
  - kanshi
  - kitty
  - lazygit
  - lsd
  - mc
  - mullvad
  - nala
  - ncdu
  - neovim
  - networkmanager-dmenu
  - npm
  - nvm
  - obsidian
  - phpstorm
  - podman-desktop
  # - qbittorrent
  # - rclone
  # - ripgrep
  # - rofi
  # - rsync
  # - screenshots
  # - ssh
  # - sshfs
  # - starship
  # - sway
  # - telnet
  # - tldr
  # - tmux
  # - vlc
  # - wireguard
  # - ytdlp
  - zoxide
  - zsh
