---
- name: "Helm | Checking for Distribution Config: {{ ansible_facts.distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts.distribution }}.yml"
  register: distribution_config

- name: "Helm | Run Tasks: {{ ansible_facts.distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_facts.distribution }}.yml"
  when: distribution_config.stat.exists

- name: Helm | Add repositories
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    url: "{{ item.url }}"
    repo_state: present
  loop: "{{ helm.repos }}"
