---
- name: "Midnight Commander | Checking for Distribution Config: {{ ansible_facts.distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts.distribution }}.yml"
  register: distribution_config

- name: "Midnight Commander | Run Tasks: {{ ansible_facts.distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_facts.distribution }}.yml"
  when: distribution_config.stat.exists
