---
- name: "System | macOS | Add alias to update software"
  ansible.builtin.blockinfile:
    append_newline: true
    block: |
      alias update="brew update && brew upgrade"
    create: true
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK (system.macosx.add-alias-to-update-software)"
    mode: "0600"
    path: "{{ item.path }}"
    prepend_newline: true
  when: item.role in default_roles
  loop:
    - role: bash
      path: "{{ ansible_facts.user_dir }}/.bashrc"
    - role: zsh
      path: "{{ ansible_facts.user_dir }}/.zshrc"

- name: "System | macOS | Configure Homebrew"
  ansible.builtin.blockinfile:
    append_newline: true
    block: |
      export HOMEBREW_INSTALL_CLEANUP=1
      export HOMEBREW_NO_ENV_HINTS=1
    create: true
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK (system.macosx.configure-homebrew)"
    mode: "0600"
    path: "{{ item.path }}"
    prepend_newline: true
  when: item.role in default_roles
  loop:
    - role: bash
      path: "{{ ansible_facts.user_dir }}/.bashrc"
    - role: zsh
      path: "{{ ansible_facts.user_dir }}/.zshrc"
