---
- name: "Git | Linux | Ensure environment.d directory exists"
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}/.config/environment.d"
    state: directory
    mode: "700"
  when: git_user_name.rc == 0 or git_user_email.rc == 0

- name: "Git | Linux | Set GIT_AUTHOR_NAME"
  ansible.builtin.lineinfile:
    create: true
    line: 'GIT_AUTHOR_NAME="{{ git_user_name.stdout }}"'
    mode: "600"
    path: "{{ ansible_facts.user_dir }}/.config/environment.d/20-git.conf"
    regexp: "GIT_AUTHOR_NAME="
    state: present
  when: git_user_name.rc == 0
  
- name: "Git | Linux | Set GIT_COMMITTER_NAME"
  ansible.builtin.lineinfile:
    create: true
    line: 'GIT_COMMITTER_NAME="{{ git_user_name.stdout }}"'
    mode: "600"
    path: "{{ ansible_facts.user_dir }}/.config/environment.d/20-git.conf"
    regexp: "GIT_COMMITTER_NAME="
    state: present
  when: git_user_name.rc == 0

- name: "Git | Linux | Set GIT_AUTHOR_EMAIL"
  ansible.builtin.lineinfile:
    create: true
    line: 'GIT_AUTHOR_EMAIL="{{ git_user_email.stdout }}"'
    mode: "600"
    path: "{{ ansible_facts.user_dir }}/.config/environment.d/20-git.conf"
    regexp: "GIT_AUTHOR_EMAIL="
    state: present
  when: git_user_email.rc == 0

- name: "Git | Set GIT_COMMITTER_EMAIL"
  ansible.builtin.lineinfile:
    create: true
    line: 'GIT_COMMITTER_EMAIL="{{ git_user_email.stdout }}"'
    mode: "600"
    path: "{{ ansible_facts.user_dir }}/.config/environment.d/20-git.conf"
    regexp: "GIT_COMMITTER_EMAIL="
    state: present
  when: git_user_email.rc == 0

- name: "Git | Linux | Add bash alias to copy branch name"
  ansible.builtin.blockinfile:
    append_newline: true
    block: |
      alias gitcb='git rev-parse --abbrev-ref HEAD | tr -d "\n" | xclip -selection clipboard'
    create: true
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK (git.alias)"
    mode: "644"
    path: "{{ ansible_facts.user_dir }}/.bashrc"
    prepend_newline: true
  when: "'bash' in default_roles"
