---
- name: "Git | macOS | Install"
  community.general.homebrew:
    name: git
    state: present

- name: "Git | macOS - bash | Add bash alias to copy branch name"
  ansible.builtin.blockinfile:
    append_newline: true
    block: |
      alias gitcb='git rev-parse --abbrev-ref HEAD | tr -d "\n" | pbcopy'
    create: true
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK (git.alias)"
    mode: "600"
    path: "{{ ansible_facts.user_dir }}/.bashrc"
    prepend_newline: true
  when: "'bash' in default_roles"

- name: "Git | macOS - zsh | Add zsh alias to copy branch name"
  ansible.builtin.blockinfile:
    append_newline: true
    block: |
      alias gitcb='git rev-parse --abbrev-ref HEAD | tr -d "\n" | pbcopy'
    create: true
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK (git.alias)"
    mode: "600"
    path: "{{ ansible_facts.user_dir }}/.zshrc"
    prepend_newline: true
  when: "'zsh' in default_roles"

- name: "Git | macOS - bash | Set GIT_AUTHOR_NAME"
  ansible.builtin.lineinfile:
    create: true
    line: 'export GIT_AUTHOR_NAME="{{ git_user_name.stdout if git_user_name is defined and git_user_name.rc is defined and git_user_name.rc == 0 else git.user.name }}"'
    mode: "600"
    path: "{{ ansible_facts.user_dir }}/.bashrc"
    regexp: "export GIT_AUTHOR_NAME="
    state: present
  when: "'bash' in default_roles"

- name: "Git | macOS - zsh | Set GIT_AUTHOR_NAME"
  ansible.builtin.lineinfile:
    create: true
    line: 'export GIT_AUTHOR_NAME="{{ git_user_name.stdout if git_user_name is defined and git_user_name.rc is defined and git_user_name.rc == 0 else git.user.name }}"'
    mode: "600"
    path: "{{ ansible_facts.user_dir }}/.zshrc"
    regexp: "export GIT_AUTHOR_NAME="
    state: present
  when: "'zsh' in default_roles"
  
- name: "Git | macOS - bash | Set GIT_COMMITTER_NAME"
  ansible.builtin.lineinfile:
    create: true
    line: 'export GIT_COMMITTER_NAME="{{ git_user_name.stdout if git_user_name is defined and git_user_name.rc is defined and git_user_name.rc == 0 else git.user.name }}"'
    mode: "600"
    path: "{{ ansible_facts.user_dir }}/.bashrc"
    regexp: "export GIT_COMMITTER_NAME="
    state: present
  when: "'bash' in default_roles"

- name: "Git | macOS - zsh | Set GIT_COMMITTER_NAME"
  ansible.builtin.lineinfile:
    create: true
    line: 'export GIT_COMMITTER_NAME="{{ git_user_name.stdout if git_user_name is defined and git_user_name.rc is defined and git_user_name.rc == 0 else git.user.name }}"'
    mode: "600"
    path: "{{ ansible_facts.user_dir }}/.zshrc"
    regexp: "export GIT_COMMITTER_NAME="
    state: present
  when: "'zsh' in default_roles"

- name: "Git | macOS - bash | Set GIT_AUTHOR_EMAIL"
  ansible.builtin.lineinfile:
    create: true
    line: 'export GIT_AUTHOR_EMAIL="{{ git_user_email.stdout if git_user_email is defined and git_user_email.rc is defined and git_user_email.rc == 0 else git.user.email }}"'
    mode: "600"
    path: "{{ ansible_facts.user_dir }}/.bashrc"
    regexp: "export GIT_AUTHOR_EMAIL="
    state: present
  when: "'bash' in default_roles"

- name: "Git | macOS - zsh | Set GIT_AUTHOR_EMAIL"
  ansible.builtin.lineinfile:
    create: true
    line: 'export GIT_AUTHOR_EMAIL="{{ git_user_email.stdout if git_user_email is defined and git_user_email.rc is defined and git_user_email.rc == 0 else git.user.email }}"'
    mode: "600"
    path: "{{ ansible_facts.user_dir }}/.zshrc"
    regexp: "export GIT_AUTHOR_EMAIL="
    state: present
  when: "'zsh' in default_roles"

- name: "Git | macOS - bash | Set GIT_COMMITTER_EMAIL"
  ansible.builtin.lineinfile:
    create: true
    line: 'export GIT_COMMITTER_EMAIL="{{ git_user_email.stdout if git_user_email is defined and git_user_email.rc is defined and git_user_email.rc == 0 else git.user.email }}"'
    mode: "600"
    path: "{{ ansible_facts.user_dir }}/.bashrc"
    regexp: "export GIT_COMMITTER_EMAIL="
    state: present
  when: "'bash' in default_roles"

- name: "Git | macOS - zsh | Set GIT_COMMITTER_EMAIL"
  ansible.builtin.lineinfile:
    create: true
    line: 'export GIT_COMMITTER_EMAIL="{{ git_user_email.stdout if git_user_email is defined and git_user_email.rc is defined and git_user_email.rc == 0 else git.user.email }}"'
    mode: "600"
    path: "{{ ansible_facts.user_dir }}/.zshrc"
    regexp: "export GIT_COMMITTER_EMAIL="
    state: present
  when: "'zsh' in default_roles"
