---
- name: "Git | macOS | Add alias to copy current branch name to clipboard"
  ansible.builtin.blockinfile:
    append_newline: true
    block: |
      alias gitcb='git rev-parse --abbrev-ref HEAD | tr -d "\n" | pbcopy'
    create: true
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK (git.copy-branch-name-alias)"
    mode: "600"
    path: "{{ item.path }}"
    prepend_newline: true
  when: item.role in default_roles
  loop:
    - role: bash
      path: "{{ ansible_facts.user_dir }}/.bashrc"
    - role: zsh
      path: "{{ ansible_facts.user_dir }}/.zshrc"

- name: "Git | macOS | Set environment variables for committing over SSH"
  ansible.builtin.blockinfile:
    append_newline: true
    block: |
      export GIT_AUTHOR_NAME="{{ git_user_name.stdout if git_user_name is defined and git_user_name.rc is defined and git_user_name.rc == 0 else git.user.name }}"
      export GIT_COMMITTER_NAME="{{ git_user_name.stdout if git_user_name is defined and git_user_name.rc is defined and git_user_name.rc == 0 else git.user.name }}"
      export GIT_AUTHOR_EMAIL="{{ git_user_email.stdout if git_user_email is defined and git_user_email.rc is defined and git_user_email.rc == 0 else git.user.email }}"
      export GIT_COMMITTER_EMAIL="{{ git_user_email.stdout if git_user_email is defined and git_user_email.rc is defined and git_user_email.rc == 0 else git.user.email }}"
    create: true
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK (git.ssh-environment-variables)"
    mode: "600"
    path: "{{ item.path }}"
    prepend_newline: true
  when: item.role in default_roles
  loop:
    - role: bash
      path: "{{ ansible_facts.user_dir }}/.bashrc"
    - role: zsh
      path: "{{ ansible_facts.user_dir }}/.zshrc"
