---
- name: "Gemini CLI | macOS | Install dependency"
  community.general.homebrew:
    name: node
    state: present

- name: "Gemini CLI | macOS | Install"
  ansible.builtin.npm:
    name: "@google/gemini-cli"
    global: yes
