---
- name: Nomad | macOS | Enable HashiCorp tap
  ansible.builtin.command:
    argv:
      - brew
      - tap
      - hashicorp/tap

- name: Nomad | macOS | Install
  community.general.homebrew:
    name: hashicorp/tap/nomad
    state: present
