---
- name: "Rofi | Checking for Distribution Config: {{ ansible_facts.distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts.distribution }}.yml"
  register: distribution_config

- name: "Rofi | Run Tasks: {{ ansible_facts.distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_facts.distribution }}.yml"
  when: distribution_config.stat.exists

- name: Rofi | Create config directory
  ansible.builtin.file:
    mode: "700"
    path: "{{ ansible_facts.user_dir }}/.config/rofi"
    state: directory

- name: Rofi | Configure
  ansible.builtin.copy:
    dest: "{{ ansible_facts.user_dir }}/.config/rofi/config.rasi"
    mode: "600"
    src: config.rasi
