---
- name: Rofi | Create config directory
  ansible.builtin.file:
    mode: "0700"
    path: "{{ ansible_facts.user_dir }}/.config/rofi"
    state: directory

- name: Rofi | Configure
  ansible.builtin.copy:
    dest: "{{ ansible_facts.user_dir }}/.config/rofi/config.rasi"
    mode: "0600"
    src: config.rasi
