---
- name: "Claude Code | macOS | Install dependency"
  community.general.homebrew:
    name: node
    state: present

- name: "Claude Code | macOS | Install"
  ansible.builtin.npm:
    name: "@anthropic-ai/claude-code"
    global: yes
