---
- name: "Vim | Checking for Distribution Config: {{ ansible_facts.distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts.distribution }}.yml"
  register: distribution_config

- name: "Vim | Run Tasks: {{ ansible_facts.distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_facts.distribution }}.yml"
  when: distribution_config.stat.exists

- name: Vim | Configure
  ansible.builtin.copy:
    dest: "{{ ansible_facts.user_dir }}/.vimrc"
    mode: "0600"
    src: vimrc
