---
- name: "Fonts | Check {{ item.font_name }} installation status"
  ansible.builtin.shell:
    cmd: fc-list | grep -i '{{ item.font_name }}'
  changed_when: false
  failed_when: false
  register: nerdfont_installed

- name: "Fonts | Install {{ item.font_name }}"
  when: nerdfont_installed.rc != 0
  block:
    - name: "Fonts | Create font directory"
      ansible.builtin.file:
        mode: "0700"
        path: "{{ ansible_facts.user_dir }}/.local/share/fonts"
        state: directory

    - name: "Fonts | Extract {{ item.font_name }}"
      ansible.builtin.unarchive:
        decrypt: false
        dest: "{{ ansible_facts.user_dir }}/.local/share/fonts"
        include:
          - "*.ttf"
        keep_newer: true
        mode: "0400"
        remote_src: true
        src: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ item.file_name }}.tar.xz
      notify: Fonts | Update font cache
